version: '3'
services:
 web:
  image: nginx:latest
  ports:
  - "80:80"
  volumes:
  - vol_html_root:/code
  - vol_site_config:/etc/nginx/conf.d/
 php:
  image: php:7-fpm
  volumes:
  - vol_html_root:/code
 mysql:
  image: mysql
  volumes:
  - vol_mysql:/var/lib/mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: netapp123 

volumes:
 vol_html_root:
  driver: netapp:latest
 vol_site_config:
  driver: netapp:latest
 vol_mysql:
  driver: netapp:latest
